name: dietgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - omegaconf=2.3.0
  - jaxtyping
  - envlight
  - accelerate
  - diffusers==0.19.3
  - transformers==4.28.1
  - pytorch-lightning
  - matplotlib
  - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  - submodules/diff-gaussian-rasterization
  - submodules/simple-knn


